<x-laravel-ai::layout>
    <p>
        -- WIP --
    </p>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce urna nulla, bibendum a scelerisque eget, maximus sit amet sapien. Nulla facilisi. Nullam urna lorem, pharetra eu varius ut, suscipit non nibh. Praesent in interdum arcu. Ut et semper leo, sed gravida metus. Cras ullamcorper nisl nec magna posuere vulputate. Morbi turpis sem, venenatis ac ullamcorper non, ultrices in urna. Curabitur non lacus sed odio feugiat feugiat in ac est. Ut at sem ultrices, pellentesque sapien ut, tempus mi. Maecenas in eleifend nibh. Nunc posuere non urna in pretium. Vivamus vel eros erat. In eget molestie orci, vitae ullamcorper tortor. Cras volutpat orci mi, eu luctus velit tristique nec. Phasellus condimentum, mauris aliquet fermentum imperdiet, ex dolor varius augue, nec bibendum libero odio ac tellus. Aliquam faucibus tellus odio, dignissim fermentum erat accumsan vitae.
    </p>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce urna nulla, bibendum a scelerisque eget, maximus sit amet sapien. Nulla facilisi. Nullam urna lorem, pharetra eu varius ut, suscipit non nibh. Praesent in interdum arcu. Ut et semper leo, sed gravida metus. Cras ullamcorper nisl nec magna posuere vulputate. Morbi turpis sem, venenatis ac ullamcorper non, ultrices in urna. Curabitur non lacus sed odio feugiat feugiat in ac est. Ut at sem ultrices, pellentesque sapien ut, tempus mi. Maecenas in eleifend nibh. Nunc posuere non urna in pretium. Vivamus vel eros erat. In eget molestie orci, vitae ullamcorper tortor. Cras volutpat orci mi, eu luctus velit tristique nec. Phasellus condimentum, mauris aliquet fermentum imperdiet, ex dolor varius augue, nec bibendum libero odio ac tellus. Aliquam faucibus tellus odio, dignissim fermentum erat accumsan vitae.
    </p>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce urna nulla, bibendum a scelerisque eget, maximus sit amet sapien. Nulla facilisi. Nullam urna lorem, pharetra eu varius ut, suscipit non nibh. Praesent in interdum arcu. Ut et semper leo, sed gravida metus. Cras ullamcorper nisl nec magna posuere vulputate. Morbi turpis sem, venenatis ac ullamcorper non, ultrices in urna. Curabitur non lacus sed odio feugiat feugiat in ac est. Ut at sem ultrices, pellentesque sapien ut, tempus mi. Maecenas in eleifend nibh. Nunc posuere non urna in pretium. Vivamus vel eros erat. In eget molestie orci, vitae ullamcorper tortor. Cras volutpat orci mi, eu luctus velit tristique nec. Phasellus condimentum, mauris aliquet fermentum imperdiet, ex dolor varius augue, nec bibendum libero odio ac tellus. Aliquam faucibus tellus odio, dignissim fermentum erat accumsan vitae.
    </p>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce urna nulla, bibendum a scelerisque eget, maximus sit amet sapien. Nulla facilisi. Nullam urna lorem, pharetra eu varius ut, suscipit non nibh. Praesent in interdum arcu. Ut et semper leo, sed gravida metus. Cras ullamcorper nisl nec magna posuere vulputate. Morbi turpis sem, venenatis ac ullamcorper non, ultrices in urna. Curabitur non lacus sed odio feugiat feugiat in ac est. Ut at sem ultrices, pellentesque sapien ut, tempus mi. Maecenas in eleifend nibh. Nunc posuere non urna in pretium. Vivamus vel eros erat. In eget molestie orci, vitae ullamcorper tortor. Cras volutpat orci mi, eu luctus velit tristique nec. Phasellus condimentum, mauris aliquet fermentum imperdiet, ex dolor varius augue, nec bibendum libero odio ac tellus. Aliquam faucibus tellus odio, dignissim fermentum erat accumsan vitae.
    </p>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce urna nulla, bibendum a scelerisque eget, maximus sit amet sapien. Nulla facilisi. Nullam urna lorem, pharetra eu varius ut, suscipit non nibh. Praesent in interdum arcu. Ut et semper leo, sed gravida metus. Cras ullamcorper nisl nec magna posuere vulputate. Morbi turpis sem, venenatis ac ullamcorper non, ultrices in urna. Curabitur non lacus sed odio feugiat feugiat in ac est. Ut at sem ultrices, pellentesque sapien ut, tempus mi. Maecenas in eleifend nibh. Nunc posuere non urna in pretium. Vivamus vel eros erat. In eget molestie orci, vitae ullamcorper tortor. Cras volutpat orci mi, eu luctus velit tristique nec. Phasellus condimentum, mauris aliquet fermentum imperdiet, ex dolor varius augue, nec bibendum libero odio ac tellus. Aliquam faucibus tellus odio, dignissim fermentum erat accumsan vitae.
    </p>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce urna nulla, bibendum a scelerisque eget, maximus sit amet sapien. Nulla facilisi. Nullam urna lorem, pharetra eu varius ut, suscipit non nibh. Praesent in interdum arcu. Ut et semper leo, sed gravida metus. Cras ullamcorper nisl nec magna posuere vulputate. Morbi turpis sem, venenatis ac ullamcorper non, ultrices in urna. Curabitur non lacus sed odio feugiat feugiat in ac est. Ut at sem ultrices, pellentesque sapien ut, tempus mi. Maecenas in eleifend nibh. Nunc posuere non urna in pretium. Vivamus vel eros erat. In eget molestie orci, vitae ullamcorper tortor. Cras volutpat orci mi, eu luctus velit tristique nec. Phasellus condimentum, mauris aliquet fermentum imperdiet, ex dolor varius augue, nec bibendum libero odio ac tellus. Aliquam faucibus tellus odio, dignissim fermentum erat accumsan vitae.
    </p>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce urna nulla, bibendum a scelerisque eget, maximus sit amet sapien. Nulla facilisi. Nullam urna lorem, pharetra eu varius ut, suscipit non nibh. Praesent in interdum arcu. Ut et semper leo, sed gravida metus. Cras ullamcorper nisl nec magna posuere vulputate. Morbi turpis sem, venenatis ac ullamcorper non, ultrices in urna. Curabitur non lacus sed odio feugiat feugiat in ac est. Ut at sem ultrices, pellentesque sapien ut, tempus mi. Maecenas in eleifend nibh. Nunc posuere non urna in pretium. Vivamus vel eros erat. In eget molestie orci, vitae ullamcorper tortor. Cras volutpat orci mi, eu luctus velit tristique nec. Phasellus condimentum, mauris aliquet fermentum imperdiet, ex dolor varius augue, nec bibendum libero odio ac tellus. Aliquam faucibus tellus odio, dignissim fermentum erat accumsan vitae.
    </p>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce urna nulla, bibendum a scelerisque eget, maximus sit amet sapien. Nulla facilisi. Nullam urna lorem, pharetra eu varius ut, suscipit non nibh. Praesent in interdum arcu. Ut et semper leo, sed gravida metus. Cras ullamcorper nisl nec magna posuere vulputate. Morbi turpis sem, venenatis ac ullamcorper non, ultrices in urna. Curabitur non lacus sed odio feugiat feugiat in ac est. Ut at sem ultrices, pellentesque sapien ut, tempus mi. Maecenas in eleifend nibh. Nunc posuere non urna in pretium. Vivamus vel eros erat. In eget molestie orci, vitae ullamcorper tortor. Cras volutpat orci mi, eu luctus velit tristique nec. Phasellus condimentum, mauris aliquet fermentum imperdiet, ex dolor varius augue, nec bibendum libero odio ac tellus. Aliquam faucibus tellus odio, dignissim fermentum erat accumsan vitae.
    </p>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce urna nulla, bibendum a scelerisque eget, maximus sit amet sapien. Nulla facilisi. Nullam urna lorem, pharetra eu varius ut, suscipit non nibh. Praesent in interdum arcu. Ut et semper leo, sed gravida metus. Cras ullamcorper nisl nec magna posuere vulputate. Morbi turpis sem, venenatis ac ullamcorper non, ultrices in urna. Curabitur non lacus sed odio feugiat feugiat in ac est. Ut at sem ultrices, pellentesque sapien ut, tempus mi. Maecenas in eleifend nibh. Nunc posuere non urna in pretium. Vivamus vel eros erat. In eget molestie orci, vitae ullamcorper tortor. Cras volutpat orci mi, eu luctus velit tristique nec. Phasellus condimentum, mauris aliquet fermentum imperdiet, ex dolor varius augue, nec bibendum libero odio ac tellus. Aliquam faucibus tellus odio, dignissim fermentum erat accumsan vitae.
    </p>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce urna nulla, bibendum a scelerisque eget, maximus sit amet sapien. Nulla facilisi. Nullam urna lorem, pharetra eu varius ut, suscipit non nibh. Praesent in interdum arcu. Ut et semper leo, sed gravida metus. Cras ullamcorper nisl nec magna posuere vulputate. Morbi turpis sem, venenatis ac ullamcorper non, ultrices in urna. Curabitur non lacus sed odio feugiat feugiat in ac est. Ut at sem ultrices, pellentesque sapien ut, tempus mi. Maecenas in eleifend nibh. Nunc posuere non urna in pretium. Vivamus vel eros erat. In eget molestie orci, vitae ullamcorper tortor. Cras volutpat orci mi, eu luctus velit tristique nec. Phasellus condimentum, mauris aliquet fermentum imperdiet, ex dolor varius augue, nec bibendum libero odio ac tellus. Aliquam faucibus tellus odio, dignissim fermentum erat accumsan vitae.
    </p>
</x-laravel-ai::layout>
